name: Download_Workflows
on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
      - name: Create base workflow folders
        run: |
          rm -rf DNA/*
          rm -rf RNA/*
          rm -rf general/*
          rm -rf nanopore/*
          rm -rf serverless/*
          mkdir tmp
      - name: Add GDC_dna_seq_no_gen3_slim_fast workflow
        run: |
          cd tmp
          wget https://github.com/Biodepot-workflows/GDC-dna-seq-no-gen3-slim-fast/tarball/main -O GDC_dna_seq_no_gen3_slim_fast.tgz
          tar -xzf GDC_dna_seq_no_gen3_slim_fast.tgz
          rm GDC_dna_seq_no_gen3_slim_fast.tgz
          cd $(ls)/workflow
          mv GDC_dna_seq_no_gen3_slim_fast ../../../DNA/GDC_dna_seq_no_gen3_slim_fast
          cd ../..
          rm -rf *
          cd ..
      - name: Add GDC_mRNA_multi_dr32chr22 workflow
        run: |
          cd tmp
          wget https://github.com/Biodepot-workflows/GDC-mRNA-multi-dr32chr22/tarball/main -O gdc_mrna_multi_dr32chr22.tgz
          tar -xzf gdc_mrna_multi_dr32chr22.tgz
          rm gdc_mrna_multi_dr32chr22.tgz
          cd $(ls)/workflow
          mv GDC_mRNA_multi_dr32chr22 ../../../RNA/GDC_mRNA_multi_dr32chr22
          cd ../..
          rm -rf *
          cd ..
      - name: Add salmon_demo workflow
        run: |
          cd tmp
          wget https://github.com/Biodepot-workflows/salmon-demo/tarball/main -O salmon_demo.tgz
          tar -xzf salmon_demo.tgz
          rm salmon_demo.tgz
          cd $(ls)/workflow
          mv salmon_demo ../../../RNA/salmon_demo
          cd ../..
          rm -rf *
          cd ..
      - name: Add focal_adhesion_segmentation workflow
        run: |
          cd tmp
          wget https://github.com/Biodepot-workflows/focal-adhesion-segmentation/tarball/main -O focal_adhesion_segmentation.tgz
          tar -xzf focal_adhesion_segmentation.tgz
          rm focal_adhesion_segmentation.tgz
          cd $(ls)/workflow
          mv focal_adhesion_segmentation ../../../general/focal_adhesion_segmentation
          cd ../..
          rm -rf *
          cd ..
      - name: Remove tmp folder
        run: |
          rm -rf tmp
      - name: Commit and push workflows
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -am "Update workflows to current versions."
          git push
